#ifndef USB_HID_H
#define USB_HID_H

#define HID_INSTANCE_CONSUMER 0
#define HID_INSTANCE_CONFIG 1

#define REPORT_ID_CONSUMER_CONTROL 1

#define REPORT_ID_CONFIG 1
#define REPORT_ID_COMMAND 2

#define CONFIG_REPORT_SIZE 6
#define COMMAND_REPORT_SIZE 1

#endif
