#ifndef USB_HID_H
#define USB_HID_H

#define HID_INSTANCE_CONSUMER 0
#define HID_INSTANCE_CONFIG 1

#define REPORT_ID_CONSUMER_CONTROL 1
#define REPORT_ID_KEYBOARD 2

#define KEY_TYPE_CONSUMER 0
#define KEY_TYPE_KEYBOARD 1

#define REPORT_ID_CONFIG 1
#define REPORT_ID_COMMAND 2

#define CONFIG_REPORT_SIZE 8
#define COMMAND_REPORT_SIZE 1

#define CONFIG_CMD_SAVE 1
#define CONFIG_CMD_LOAD 2
#define CONFIG_CMD_DEFAULTS 3
#define CONFIG_CMD_BOOTSEL 4

#endif
