// Command gen-config reads the output of the gen_config C program from stdin
// and generates Go source code for the config struct, constants, and
// encode/decode functions.
package main

import (
	"bufio"
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"strconv"
	"strings"
	"text/template"
)

// Map the C symbol name to the Go symbol name.
var constNameMap = map[string]string{
	"CONFIG_MAGIC":        "configMagic",
	"REPORT_ID_CONFIG":    "reportIDConfig",
	"REPORT_ID_COMMAND":   "reportIDCommand",
	"CONFIG_CMD_SAVE":     "cmdSave",
	"CONFIG_CMD_LOAD":     "cmdLoad",
	"CONFIG_CMD_DEFAULTS": "cmdDefaults",
	"CONFIG_CMD_BOOTSEL":  "cmdBootsel",
	"KEY_TYPE_CONSUMER":   "keyTypeConsumer",
	"KEY_TYPE_KEYBOARD":   "keyTypeKeyboard",
	"COMMAND_REPORT_SIZE": "commandReportSize",
}

// These identifies components of names that should be rendered in all caps.
// Without this we would get typeCw instead of typeCW.
var abbreviations = map[string]bool{
	"cw":  true,
	"ccw": true,
	"id":  true,
}

// Represents a single const value.
type constEntry struct {
	GoName string
	Value  string
}

// Maps fields in the C config_t struct to their Go equivalents.
type field struct {
	cName  string
	goName string
	goType string
	offset int
	size   int
}

func (f field) GoName() string { return f.goName }
func (f field) GoType() string { return f.goType }

// Convert a C name (type_cw) to a Go name (typeCW).
func cNameToGo(name string) string {
	parts := strings.Split(name, "_")
	result := parts[0]
	for _, p := range parts[1:] {
		if abbreviations[strings.ToLower(p)] {
			result += strings.ToUpper(p)
		} else {
			result += strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return result
}

// Select the appropriate data type for a field based on its size.
func sizeToGoType(size int) string {
	switch size {
	case 1:
		return "uint8"
	case 2:
		return "uint16"
	case 4:
		return "uint32"
	default:
		log.Fatalf("unsupported field size: %d", size)
		return ""
	}
}

// Return the start of a field in the config struct.
func (f field) BufOffset() int {
	return f.offset + 1
}

// Return the end of a field in the config struct.
func (f field) BufEnd() int {
	return f.BufOffset() + f.size
}

// Generate code to read a field value from the buffer.
func (f field) ReadExpr() string {
	off := f.BufOffset()
	switch f.goType {
	case "uint8":
		return fmt.Sprintf("buf[%d]", off)
	case "uint16":
		return fmt.Sprintf("binary.LittleEndian.Uint16(buf[%d:%d])", off, f.BufEnd())
	case "uint32":
		return fmt.Sprintf("binary.LittleEndian.Uint32(buf[%d:%d])", off, f.BufEnd())
	}
	panic("unreachable")
}

// Generate code to write a field value to the buffer.
func (f field) WriteStmt() string {
	off := f.BufOffset()
	expr := "cfg." + f.goName
	switch f.goType {
	case "uint8":
		return fmt.Sprintf("buf[%d] = %s", off, expr)
	case "uint16":
		return fmt.Sprintf("binary.LittleEndian.PutUint16(buf[%d:%d], %s)", off, f.BufEnd(), expr)
	case "uint32":
		return fmt.Sprintf("binary.LittleEndian.PutUint32(buf[%d:%d], %s)", off, f.BufEnd(), expr)
	}
	panic("unreachable")
}

var tmpl = template.Must(template.New("config").Parse(`// Code generated by gen-config from gen_config output. DO NOT EDIT.

package main

import (
	"encoding/binary"
	"log"
)

const (
	configReportSize = {{.ReportSize}}
{{- range .Consts}}
	{{.GoName}} = {{.Value}}
{{- end}}
)

type config struct {
{{- range .Fields}}
	{{.GoName}} {{.GoType}}
{{- end}}
}

func configFromBuf(buf []byte) config {
	if len(buf) != configReportSize+1 {
		log.Fatalf("device configuration is invalid")
	}
	magic := binary.LittleEndian.Uint32(buf[1:5])
	if magic != configMagic {
		log.Fatalf("firmware version mismatch (expected magic 0x%08X, got 0x%08X); please update firmware or vkcfg", configMagic, magic)
	}
	return config{
{{- range .Fields}}
		{{.GoName}}: {{.ReadExpr}},
{{- end}}
	}
}

func configToBuf(reportId uint8, cfg config) []byte {
	buf := make([]byte, configReportSize+1)
	buf[0] = reportId
	binary.LittleEndian.PutUint32(buf[1:5], configMagic)
{{- range .Fields}}
	{{.WriteStmt}}
{{- end}}
	return buf
}
`))

// Wire-only fields are part of the binary protocol but not exposed in the Go config struct.
var wireOnly = map[string]bool{
	"magic": true,
	"crc32": true,
}

func main() {
	log.SetFlags(0)
	log.SetPrefix("gen-config: ")

	var reportSize int
	var fields []field
	var consts []constEntry

	scanner := bufio.NewScanner(os.Stdin)
	for scanner.Scan() {
		parts := strings.Fields(scanner.Text())
		if len(parts) == 0 {
			continue
		}
		switch parts[0] {
		case "report_size":
			v, err := strconv.Atoi(parts[1])
			if err != nil {
				log.Fatalf("bad report_size: %s", parts[1])
			}
			reportSize = v
		case "field":
			name := parts[1]
			offset, _ := strconv.Atoi(parts[2])
			size, _ := strconv.Atoi(parts[3])
			if !wireOnly[name] {
				fields = append(fields, field{
					cName:  name,
					goName: cNameToGo(name),
					goType: sizeToGoType(size),
					offset: offset,
					size:   size,
				})
			}
		case "const":
			cName := parts[1]
			value := parts[2]
			goName, ok := constNameMap[cName]
			if !ok {
				log.Fatalf("unknown constant: %s", cName)
			}
			consts = append(consts, constEntry{GoName: goName, Value: value})
		}
	}
	if err := scanner.Err(); err != nil {
		log.Fatalf("reading stdin: %v", err)
	}
	if reportSize == 0 {
		log.Fatal("no report_size in input")
	}

	var b bytes.Buffer
	err := tmpl.Execute(&b, struct {
		ReportSize int
		Consts     []constEntry
		Fields     []field
	}{reportSize, consts, fields})
	if err != nil {
		log.Fatalf("executing template: %v", err)
	}

	src, err := format.Source(b.Bytes())
	if err != nil {
		log.Fatalf("formatting generated code: %v", err)
	}
	os.Stdout.Write(src)
}
