// Command gen-config reads the output of the gen_config C program from stdin
// and generates Go source code for the config struct, constants, and
// encode/decode functions.
package main

import (
	"bufio"
	"fmt"
	"go/format"
	"log"
	"os"
	"strconv"
	"strings"
)

var constNameMap = map[string]string{
	"CONFIG_MAGIC":        "configMagic",
	"REPORT_ID_CONFIG":    "reportIDConfig",
	"REPORT_ID_COMMAND":   "reportIDCommand",
	"CONFIG_CMD_SAVE":     "cmdSave",
	"CONFIG_CMD_LOAD":     "cmdLoad",
	"CONFIG_CMD_DEFAULTS": "cmdDefaults",
	"CONFIG_CMD_BOOTSEL":  "cmdBootsel",
	"KEY_TYPE_CONSUMER":   "keyTypeConsumer",
	"KEY_TYPE_KEYBOARD":   "keyTypeKeyboard",
	"COMMAND_REPORT_SIZE": "commandReportSize",
}

var abbreviations = map[string]bool{
	"cw":  true,
	"ccw": true,
	"id":  true,
}

type field struct {
	cName  string
	goName string
	goType string
	offset int
	size   int
}

func cNameToGo(name string) string {
	parts := strings.Split(name, "_")
	result := parts[0]
	for _, p := range parts[1:] {
		if abbreviations[strings.ToLower(p)] {
			result += strings.ToUpper(p)
		} else {
			result += strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return result
}

func sizeToGoType(size int) string {
	switch size {
	case 1:
		return "uint8"
	case 2:
		return "uint16"
	case 4:
		return "uint32"
	default:
		log.Fatalf("unsupported field size: %d", size)
		return ""
	}
}

func goReadExpr(goType string, bufOffset int) string {
	switch goType {
	case "uint8":
		return fmt.Sprintf("buf[%d]", bufOffset)
	case "uint16":
		return fmt.Sprintf("binary.LittleEndian.Uint16(buf[%d:%d])", bufOffset, bufOffset+2)
	case "uint32":
		return fmt.Sprintf("binary.LittleEndian.Uint32(buf[%d:%d])", bufOffset, bufOffset+4)
	}
	panic("unreachable")
}

func goWriteStmt(goType string, bufOffset int, expr string) string {
	switch goType {
	case "uint8":
		return fmt.Sprintf("\tbuf[%d] = %s", bufOffset, expr)
	case "uint16":
		return fmt.Sprintf("\tbinary.LittleEndian.PutUint16(buf[%d:%d], %s)", bufOffset, bufOffset+2, expr)
	case "uint32":
		return fmt.Sprintf("\tbinary.LittleEndian.PutUint32(buf[%d:%d], %s)", bufOffset, bufOffset+4, expr)
	}
	panic("unreachable")
}

// Wire-only fields are part of the binary protocol but not exposed in the Go config struct.
var wireOnly = map[string]bool{
	"magic": true,
	"crc32": true,
}

func main() {
	log.SetFlags(0)
	log.SetPrefix("gen-config: ")

	var reportSize int
	var fields []field
	type constEntry struct {
		goName string
		value  string
	}
	var consts []constEntry

	scanner := bufio.NewScanner(os.Stdin)
	for scanner.Scan() {
		parts := strings.Fields(scanner.Text())
		if len(parts) == 0 {
			continue
		}
		switch parts[0] {
		case "report_size":
			v, err := strconv.Atoi(parts[1])
			if err != nil {
				log.Fatalf("bad report_size: %s", parts[1])
			}
			reportSize = v
		case "field":
			name := parts[1]
			offset, _ := strconv.Atoi(parts[2])
			size, _ := strconv.Atoi(parts[3])
			if !wireOnly[name] {
				fields = append(fields, field{
					cName:  name,
					goName: cNameToGo(name),
					goType: sizeToGoType(size),
					offset: offset,
					size:   size,
				})
			}
		case "const":
			cName := parts[1]
			value := parts[2]
			goName, ok := constNameMap[cName]
			if !ok {
				log.Fatalf("unknown constant: %s", cName)
			}
			consts = append(consts, constEntry{goName, value})
		}
	}
	if err := scanner.Err(); err != nil {
		log.Fatalf("reading stdin: %v", err)
	}
	if reportSize == 0 {
		log.Fatal("no report_size in input")
	}

	var b strings.Builder

	fmt.Fprintln(&b, "// Code generated by gen-config from gen_config output. DO NOT EDIT.")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "package main")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, `import (`)
	fmt.Fprintln(&b, `	"encoding/binary"`)
	fmt.Fprintln(&b, `	"log"`)
	fmt.Fprintln(&b, `)`)
	fmt.Fprintln(&b)

	// Constants.
	fmt.Fprintln(&b, "const (")
	fmt.Fprintf(&b, "\tconfigReportSize = %d\n", reportSize)
	for _, c := range consts {
		fmt.Fprintf(&b, "\t%s = %s\n", c.goName, c.value)
	}
	fmt.Fprintln(&b, ")")
	fmt.Fprintln(&b)

	// Struct.
	fmt.Fprintln(&b, "type config struct {")
	for _, f := range fields {
		fmt.Fprintf(&b, "\t%s %s\n", f.goName, f.goType)
	}
	fmt.Fprintln(&b, "}")
	fmt.Fprintln(&b)

	// configFromBuf.
	fmt.Fprintln(&b, "func configFromBuf(buf []byte) config {")
	fmt.Fprintln(&b, "\tif len(buf) != configReportSize+1 {")
	fmt.Fprintln(&b, `		log.Fatalf("device configuration is invalid")`)
	fmt.Fprintln(&b, "\t}")
	fmt.Fprintln(&b, "\tmagic := binary.LittleEndian.Uint32(buf[1:5])")
	fmt.Fprintln(&b, "\tif magic != configMagic {")
	fmt.Fprintln(&b, `		log.Fatalf("firmware version mismatch (expected magic 0x%08X, got 0x%08X); please update firmware or vkcfg", configMagic, magic)`)
	fmt.Fprintln(&b, "\t}")
	fmt.Fprintln(&b, "\treturn config{")
	for _, f := range fields {
		bufOffset := f.offset + 1 // +1 for report ID prefix byte
		fmt.Fprintf(&b, "\t\t%s: %s,\n", f.goName, goReadExpr(f.goType, bufOffset))
	}
	fmt.Fprintln(&b, "\t}")
	fmt.Fprintln(&b, "}")
	fmt.Fprintln(&b)

	// configToBuf.
	fmt.Fprintln(&b, "func configToBuf(reportId uint8, cfg config) []byte {")
	fmt.Fprintln(&b, "\tbuf := make([]byte, configReportSize+1)")
	fmt.Fprintln(&b, "\tbuf[0] = reportId")
	fmt.Fprintln(&b, "\tbinary.LittleEndian.PutUint32(buf[1:5], configMagic)")
	for _, f := range fields {
		bufOffset := f.offset + 1
		fmt.Fprintln(&b, goWriteStmt(f.goType, bufOffset, "cfg."+f.goName))
	}
	fmt.Fprintln(&b, "\treturn buf")
	fmt.Fprintln(&b, "}")

	src, err := format.Source([]byte(b.String()))
	if err != nil {
		log.Fatalf("formatting generated code: %v", err)
	}
	os.Stdout.Write(src)
}
